# Generated by Django 4.2.1 on 2023-05-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
