# Generated by Django 4.2.1 on 2023-05-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_remove_item_price_item_date_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
    ]
