# Generated by Django 4.2.1 on 2023-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_date_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='item',
            name='camera_used',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='picture_editor_used',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
